# Generated by Django 3.2.9 on 2021-11-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField()),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('short_description', models.CharField(blank=True, default='', max_length=250)),
                ('descriptions', models.TextField()),
                ('url', models.CharField(blank=True, default='', max_length=100)),
                ('github', models.CharField(blank=True, default='', max_length=200)),
                ('video', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
